/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tomaschlapek.nba.core.ui

import androidx.compose.ui.graphics.Color

/**
 *  Color palette for the app
 *  Generated by Material Color Palette (https://m3.material.io/theme-builder#/custom)
 */

// Primary colors - NBA Blue
val md_theme_light_primary = Color(0xFF1D428A) // NBA Blue
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC8D6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3D)
val md_theme_light_secondary = Color(0xFFC9082A) // NBA Red
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onSecondaryContainer = Color(0xFF410002)
val md_theme_light_tertiary = Color(0xFFFDB927) // NBA Gold
val md_theme_light_onTertiary = Color(0xFF000000)
val md_theme_light_tertiaryContainer = Color(0xFFFFE5B4)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFA9C0FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1D428A)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)

// Toolbar colors
val md_theme_light_toolbar = Color(0xFF2C3E50) // Dark blue-grey for toolbar
val md_theme_light_onToolbar = Color(0xFFFFFFFF) // White text on toolbar

val md_theme_dark_primary = Color(0xFFA9C0FF)
val md_theme_dark_onPrimary = Color(0xFF002F63)
val md_theme_dark_primaryContainer = Color(0xFF00458A)
val md_theme_dark_onPrimaryContainer = Color(0xFFC8D6FF)
val md_theme_dark_secondary = Color(0xFFFFB4AB)
val md_theme_dark_onSecondary = Color(0xFF690005)
val md_theme_dark_secondaryContainer = Color(0xFF93000A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_tertiary = Color(0xFFCCB480)
val md_theme_dark_onTertiary = Color(0xFF462B00)
val md_theme_dark_tertiaryContainer = Color(0xFF633F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE5B4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF1D428A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA9C0FF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)

// Toolbar colors
val md_theme_dark_toolbar = Color(0xFF1A2634) // Darker blue-grey for dark theme toolbar
val md_theme_dark_onToolbar = Color(0xFFFFFFFF) // White text on dark theme toolbar

val seed = Color(0xFF1D428A) // NBA Blue
